version: '2'

services:

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx.${APP_ENV}.dockerfile
    links:
      - stocks-api:stocks-api
    ports:
      - "80:80"
    networks:
      - stocks-network

  # creating the express api
  stocks-api:
    build:
      context: .
      dockerfile: ./docker/node.dockerfile
    volumes:
      - .:/var/www/stocks-api
    working_dir: /var/www/stocks-api
    env_file:
      - ./docker/env/app.${APP_ENV}.env
    ports:
      - "8080:8080"
    networks:
      - stocks-network

  # creating the mongo database
  stocks-database:
    image: mongo
    networks:
      - stocks-network

networks:
  stocks-network:
    driver: bridge
