version: '2'

services:

  # creating the express api
  stocks-api:
    build:
      context: .
      dockerfile: ./docker/node.dockerfile
    volumes:
      - .:/var/www/stocks-api
    working_dir: /var/www/stocks-api
    env_file:
      - ./docker/env/app.${APP_ENV}.env
    ports:
      - "8080:8080"
    networks:
      - stocksapp-network

  # creating the mongo database
  stocks-database:
    image: mongo
    networks:
      - stocksapp-network

networks:
  stocksapp-network:
    driver: bridge
